name: CI/CD - Build and Deploy to Cloudflare Pages

on: push: branches: [ main ] workflow_dispatch:

jobs: deploy: name: Build & Deploy runs-on: ubuntu-latest permissions: contents: read deployments: write env: CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }} # Optional but recommended if you have multiple CF accounts: # CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }} steps: - name: Checkout uses: actions/checkout@v4

  - name: Setup Node
    uses: actions/setup-node@v4
    with:
      node-version: '20'
      cache: 'npm'

  - name: Install dependencies
    run: npm ci

  - name: Build
    run: npm run build

  - name: Debug secrets presence (safe)
    run: |
      if [ -z "${CLOUDFLARE_API_TOKEN}" ]; then
        echo "CLOUDFLARE_API_TOKEN is missing" >&2
        exit 1
      else
        echo "CLOUDFLARE_API_TOKEN is set"
      fi

  - name: Wrangler whoami (debug)
    run: npx --yes wrangler@4.32.0 --verbose whoami

  - name: Deploy with Wrangler (verbose)
    run: |
      # Hardcode the project name to remove one variable
      PROJECT="webapp-87q"
      echo "Deploying to Pages project: ${PROJECT}"
      npx --yes wrangler@4.32.0 --verbose pages deploy dist --project-name "${PROJECT}" --commit-dirty=true
